on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Test CoastSeg Pip Installation
jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        # tensorflow supports up to python 3.10
        os: [ubuntu-latest, windows-latest, macos-latest]
        env: [ci/envs/310-coastseg.yaml]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          miniconda-version: "latest"
      - run: |
          conda info
          conda list
      - name: Install gdal and geopandas from conda
        run: |
          conda install -c conda-forge gdal geopandas -y
      - name: Install coastseg with pip install -e .
        run: |
          pip install -e . --user
      - name: Pip install pytest
        run: |
          pip install pytest
      - name: Test with pytest
        run: |
          cd tests
          python -m pytest
