on:
  push:
    branches: [pypi_workflow]
  pull_request:
    branches: [pypi_workflow]

name: Test CoastSeg
jobs:
  Test:
    name: ${{ matrix.os }}, ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.10, 3.11]
        include:
          - env: ci/envs/39-coastseg.yaml
            python-version: 3.9
          - env: ci/envs/310-coastseg.yaml
            python-version: 3.10
          - env: ci/envs/311-coastseg.yaml
            python-version: 3.11

    steps:
      - uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: ${{ matrix.env }}
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
      - run: |
          conda info
          conda list
      - name: Install coastseg from pip
        run: |
          python -m pip install --upgrade pip
          pip install coastseg
      - name: Pip install pytest
        run: |
          pip install pytest
      - name: Test with pytest
        run: |
          cd tests
          python -m pytest
