on:
    push:
        branches: [packaging/beta_package, packaging/updating_dependencies]
    pull_request:
        branches: [packaging/beta_package, packaging/updating_dependencies]

name: Windows build
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.9
      - name: Install GDAL
        run: conda install -c conda-forge gdal=3.4.0 --yes
      - name: Test GDAL installation
        run: |
          python -c "from osgeo import gdal"
          gdalinfo --version
      - name: Install Conda Dependencies
        run: conda install -c conda-forge jupyter geopandas --yes
      - name: Test Conda Dependencies installation
        run: |
          python -c "import geopandas"
          python -c "import jupyter"
      - name: Install coastseg-beta-package 0.0.5
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir Cython
          pip install coastseg-beta-package==0.0.5